/**
 * Moderation-specific types (MediaPart, ModerationResult, LLM reply shape).
 * Generic Telegram/Env types live in core/types.ts.
 */

import { ADMIN_STATUSES } from '../../core/types';

/** Telegram ChatMember status values relevant for admin detection. */
export { ADMIN_STATUSES };

/** Which pieces of a message we resolved and are sending to the LLM. */
export interface MediaPart {
  kind: 'photo' | 'video' | 'document' | 'animation';
  file_id: string;
  /** base64 data URL (data:image/...;base64,...) — never a public URL,
   * so the bot token is not leaked to the LLM provider and Workers AI's
   * multimodal URL-domain allowlist is not hit. */
  dataUrl: string;
  mimeType?: string;
}

/** Result of the LLM moderation call. */
export interface ModerationResult {
  flag: boolean;
  reason: string;
  /**
   * Optional kind/harmless funny reply generated by the SAME moderation
   * completion when the funny-response feature is enabled. Falls back to a
   * generic safe line at the call site.
   */
  funResponse?: string;
  /**
   * The raw text returned by the LLM (for audit logging). May be empty when
   * the result was synthesized from an error/fallback.
   */
  llmResponse?: string;
}

/**
 * Shape of the parsed LLM JSON response. `fun_response` is optional and is
 * only requested when the funny-response feature is enabled.
 */
export interface JsonModerationReply {
  flag?: unknown;
  reason?: unknown;
  /** Optional funny reply, requested only when ENABLE_FUNRESPONSE is on. */
  fun_response?: unknown;
}
